package ai.rever.boss.plugin.dynamic.llmrpa

import ai.rever.boss.plugin.logging.BossLogger
import ai.rever.boss.plugin.logging.LogCategory
import java.io.File
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Writes a generated plan where the RPA Engine will find it.
 *
 * This plugin generated action lists that nothing could run: the engine loads configurations from
 * disk (`RpaEngineSettings` scans `~/.boss/config/rpaengine`, the recorder's directory, and
 * Downloads) and there was no path from here into any of them. So "Execute Instruction" produced a
 * plan and stopped, with a ▶ icon promising otherwise.
 *
 * A file rather than an API call, because that is the interface the engine already has - the RPA
 * Recorder hands off the same way. No new cross-plugin surface, and the plan is inspectable and
 * re-runnable afterwards.
 *
 * **Deliberately does not run anything.** Driving a browser is not something to start without a
 * person deciding to: the engine's own Run button stays the trigger. This gets the plan in front
 * of it.
 */
internal object RpaEngineHandoff {
    private val logger = BossLogger.forComponent("LlmRpaHandoff")

    private val json = Json { prettyPrint = true; encodeDefaults = true }

    /**
     * Where the engine looks first. Created on demand, as the engine itself does.
     *
     * A parameter on [write] rather than only this default, because the first version of the
     * tests wrote into the real directory and left four junk configurations in the user's engine
     * list. A path read from `user.home` with no seam is not testable without side effects.
     */
    private val defaultConfigDir: File
        get() = File(System.getProperty("user.home"), ".boss/config/rpaengine")

    /**
     * The engine's own on-disk shape.
     *
     * A separate model from [LLMRpaResponse] because the two disagree in ways that would silently
     * produce a config the engine cannot read: it wraps actions in `{name, description, actions}`
     * rather than `{configuration, status, message}`, and it names the field `actionType` where
     * this plugin (and its prompt) say `action_type`. Mapping in one place is what keeps that from
     * being discovered at run time.
     */
    @Serializable
    private data class EngineConfiguration(
        val name: String,
        val description: String = "",
        val actions: List<EngineAction>,
    )

    @Serializable
    private data class EngineAction(
        val name: String = "",
        @SerialName("actionType") val actionType: String = "default",
        val type: String,
        val selector: SelectorInfo,
        val value: String? = null,
        val meta: Map<String, String>? = null,
    )

    /**
     * Write [actions] as a configuration named after [instruction].
     *
     * Returns the file, or null when writing failed - the caller reports that rather than leaving
     * the user to wonder why the engine's list is empty.
     */
    fun write(
        instruction: String,
        actions: List<RpaActionConfig>,
        configDir: File = defaultConfigDir,
    ): File? =
        runCatching {
            val dir = configDir.apply { mkdirs() }
            val file = File(dir, "${safeName(instruction)}.json")
            val config =
                EngineConfiguration(
                    name = instruction.take(MAX_NAME_CHARS),
                    description = "Generated by LLM RPA from: $instruction",
                    actions = actions.map { it.toEngineAction() },
                )
            file.writeText(json.encodeToString(EngineConfiguration.serializer(), config))
            file
        }.onFailure { error ->
            logger.warn(
                LogCategory.GENERAL,
                "Could not write the generated plan for the RPA Engine",
                mapOf("error" to (error.message ?: "unknown")),
            )
        }.getOrNull()

    private fun RpaActionConfig.toEngineAction() =
        EngineAction(
            name = name,
            actionType = action_type,
            type = type,
            selector = selector,
            value = value,
            meta = meta,
        )

    /**
     * A filename from an instruction: word characters only, so nothing in a sentence can name a
     * path or collide with the engine's own settings file.
     */
    private fun safeName(instruction: String): String {
        val slug =
            instruction
                .lowercase()
                .replace(Regex("[^a-z0-9]+"), "-")
                .trim('-')
                .take(MAX_SLUG_CHARS)
                .ifBlank { "plan" }
        return "llm-rpa-$slug"
    }

    private const val MAX_SLUG_CHARS = 40
    private const val MAX_NAME_CHARS = 80
}
